export interface IMailService {
  receiveDefaultPassword(
    email: string,
    autoGeneratedPassword: string,
  ): Promise<void>;
  receiveOnResetPassword(
    email: string,
    autoGeneratedPassword: string,
  ): Promise<void>;
}
