import { IMailService } from './mail.interface';
import { Mailer } from './mailer';

export class MailService extends Mailer implements IMailService {
  public async receiveDefaultPassword(
    email: string,
    autoGeneratedPassword: string,
  ): Promise<void> {
    const subject = 'Your Default Password';
    const body = `Your password is ${autoGeneratedPassword}. Please login and change your password immediately.`;

    await this.sendMail([email], subject, body);
  }
}
