import { IMailService } from './mail.interface';
import { Mailer } from './mailer';

export class MailService extends Mailer implements IMailService {
  public async receiveOnResetPassword(
    email: string,
    autoGeneratedPassword: string,
  ): Promise<void> {
    const subject = 'Mật khẩu mới';
    const body = `Mật khẩu đăng nhập của bạn là ${autoGeneratedPassword}. Vui lòng đăng nhập và thay đổi mật khẩu của bạn.`;

    await this.sendMail([email], subject, body);
  }
  public async receiveDefaultPassword(
    email: string,
    autoGeneratedPassword: string,
  ): Promise<void> {
    const subject = 'Mật khẩu mặc định';
    const body = `Mật khẩu đăng nhập của bạn là ${autoGeneratedPassword}. Vui lòng đăng nhập và thay đổi mật khẩu của bạn.`;

    await this.sendMail([email], subject, body);
  }

  public async sendOnCreateLeaveRequest(
    email: string,
    leaveType: string,
    startDate: string,
    endDate: string,
    reason: string,
  ): Promise<void> {
    const subject = 'Thông báo đăng ký nghỉ phép';
    const body = `Có đăng ký nghỉ phép ${leaveType} từ ${startDate} đến ${endDate} với lý do ${reason}. Vui lòng đăng nhập vào hệ thống để xem chi tiết.`;

    await this.sendMail([email], subject, body);
  }
}
