import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma/prisma.service';
import { createUserDto, userInformationDto } from './user.dto';
import {
  ServiceFailure,
  ServiceResponse,
  ServiceResponseStatus,
} from 'src/serviceResponse';
import { UserFailure } from 'src/enumTypes/failure.enum';
import { MailService } from 'src/mail/mail.service';
import { autoGeneratedPassword, hashPassword } from 'src/utils/password';

@Injectable()
export class UserService {
  constructor(
    private prisma: PrismaService,
    private mailService: MailService,
  ) {}

  public async createUser(
    dto: createUserDto,
  ): Promise<
    ServiceResponse<
      { user: createUserDto; password: string },
      ServiceFailure<UserFailure>
    >
  > {
    const existingUser = await this.prisma.user.findUnique({
      where: {
        email: dto.email,
      },
    });

    if (existingUser) {
      return {
        status: ServiceResponseStatus.Failed,
        failure: {
          reason: UserFailure.USER_ALREADY_EXISTS,
        },
      };
    }
    const generatedPassword = autoGeneratedPassword();
    const hashedPassword = await hashPassword(generatedPassword);

    try {
      await this.mailService.receiveDefaultPassword(
        dto.email,
        generatedPassword,
      );
    } catch (err) {
      return {
        status: ServiceResponseStatus.Failed,
        failure: {
          reason: err,
        },
      };
    }

    const user = await this.prisma.user.create({
      data: {
        email: dto.email,
        fullName: dto.fullName,
        password: hashedPassword,
        gender: dto.gender,
        status: dto.status,
        roleId: dto.roleId,
      },

      select: {
        id: true,
        email: true,
        fullName: true,
        password: true,
        gender: true,
        status: true,
        roleId: true,
      },
    });

    return {
      status: ServiceResponseStatus.Success,
      result: { user, password: generatedPassword },
    };
  }

  public async getAllEmails(): Promise<string[]> {
    const emails = await this.prisma.user.findMany({
      select: {
        email: true,
      },
    });

    return emails.map((email) => email.email);
  }

  public async updatePersonalInformation(
    email: string,
    dto: userInformationDto,
  ): Promise<ServiceResponse<userInformationDto, ServiceFailure<UserFailure>>> {
    const user = await this.prisma.user.findUnique({
      where: {
        email: email,
      },
    });

    if (!user) {
      return {
        status: ServiceResponseStatus.Failed,
        failure: {
          reason: UserFailure.USER_NOT_FOUND,
        },
      };
    }

    await this.prisma.user.update({
      where: {
        id: user.id,
      },
      data: {
        fullName: dto.fullName,
        firstName: dto.firstName,
        lastName: dto.lastName,
        gender: dto.gender,
        dateOfBirth: new Date(dto.dateOfBirth),
        phoneNumber: dto.phoneNumber,
        address: dto.address,
        nationality: dto.nationality,
        avatar: dto.avatar,
      },
    });

    return {
      status: ServiceResponseStatus.Success,
    };
  }

  public async getAllUsers(): Promise<
    ServiceResponse<userInformationDto[], ServiceFailure<UserFailure>>
  > {
    const userInformationDto = await this.prisma.user.findMany({
      select: {
        email: true,
        fullName: true,
        firstName: true,
        lastName: true,
        gender: true,
        dateOfBirth: true,
        phoneNumber: true,
        address: true,
        nationality: true,
        avatar: true,
        status: true,
        role: {
          select: {
            name: true,
          },
        },
      },
    });

    return {
      status: ServiceResponseStatus.Success,
      result: userInformationDto,
    };
  }
}
