import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma/prisma.service';
import { createUserDto } from './dto/user.dto';
import {
  ServiceFailure,
  ServiceResponse,
  ServiceResponseStatus,
} from 'src/serviceResponse';
import { CreateUserFailure } from 'src/enumTypes/enumFailures/user.failure.enum';
import { MailService } from 'src/mail/mail.service';
import { autoGeneratedPassword, hashPassword } from 'src/utils/password';

@Injectable()
export class UserService {
  constructor(
    private prisma: PrismaService,
    private mailService: MailService,
  ) {}

  public async createUser(
    dto: createUserDto,
  ): Promise<
    ServiceResponse<
      { user: createUserDto; password: string },
      ServiceFailure<CreateUserFailure>
    >
  > {
    const existingUser = await this.prisma.user.findUnique({
      where: {
        email: dto.email,
      },
    });

    if (existingUser) {
      return {
        status: ServiceResponseStatus.Failed,
        failure: {
          reason: CreateUserFailure.USER_ALREADY_EXISTS,
        },
      };
    }
    const generatedPassword = autoGeneratedPassword();
    const hashedPassword = await hashPassword(generatedPassword);

    try {
      await this.mailService.receiveDefaultPassword(
        dto.email,
        generatedPassword,
      );
    } catch (err) {
      return {
        status: ServiceResponseStatus.Failed,
        failure: {
          reason: err,
        },
      };
    }

    const user = await this.prisma.user.create({
      data: {
        email: dto.email,
        fullName: dto.fullName,
        password: hashedPassword,
        gender: dto.gender,
        status: dto.status,
        roleId: dto.roleId,
      },

      select: {
        id: true,
        email: true,
        fullName: true,
        password: true,
        gender: true,
        status: true,
        roleId: true,
      },
    });

    return {
      status: ServiceResponseStatus.Success,
      result: { user, password: generatedPassword },
    };
  }

  public async getAllEmails(): Promise<string[]> {
    const emails = await this.prisma.user.findMany({
      select: {
        email: true,
      },
    });

    return emails.map((email) => email.email);
  }
}
